spring:
  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USER}
    password: ${AUTH_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 600000
      initialization-fail-timeout: 0

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
